version: "3.7"
services:
  frontend-service:
    image: frontend
    deploy:
      replicas: 2
    container_name: frontend
    build: FrontEnd/
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DB=${MYSQL_DB}
    - MYSQL_DB_TEST=${MYSQL_DB_TEST}
    - SECRET_KEY=${SECRET_KEY}

  nginx:
    image: nginx:latest
    deploy:
      replicas: 2
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend-service